### ISSUE TITLE
As a developer I want the salt event proxy to have proper CORS policy such that we can see network information from z-pattern.

### ISSUE THREAD

**Issue by xuther** [byuoitav/team#141]
- [x] Put new binary into pi's across the ITB
- [x] Write script to migrate binary to rest of campus, using salt
- [x] Test the migration script and binary

**Comment by jpw547** [comment]
I manually moved the binary to all of the pis in the ITB and saw no issues as a result of doing that. I ran a command on the salt master to stop the salt-event-proxy service on all the pis that we have, then another command for them all to get the binary, and then a third command to start the service on all of the pis again. These commands were executed on ALL of the pis across campus. 

This issue is now resolved to my knowledge, because the network errors that we were seeing before have been resolved.
