### ISSUE TITLE
Independent audio device layout on Pi's need to be fixed.

### ISSUE THREAD

**Issue by jpw547** [byuoitav/team#164]
- [x] Figure out the bug why the microphone audio layout is pushed to the left.

**Comment by dannyrandall** [comment]
It looks like the layout is only broken on pi's that aren't on the latest version of Chromium, and they can't be updated because the latest version for jessie doesn't work. Therefore, to fix this issue, we just need to update the affected pi's to stretch and it should work. I'll update the pi in 1010 (`cp2`) because I know that one is out of date.
