### ISSUE TITLE
Updates to SMEE round 1

### ISSUE THREAD

**Issue by mandersonpjm** [byuoitav/team#798]

**Comment by thailandmatt** [comment]
Alert table
- [ ] Change severity to just be a striped band in the first column
- [ ] If maintenance is in the tags, add an icon to the first column
- [ ] Add age to the table
- [ ] Add the most recent note to the table
- [ ] Get rid of Incident ID column
- [ ] Add next time available

Overview page
- [ ] Make the notes a read-only display with a pencil that then edits in place with a update and cancel button (something like http://jsfiddle.net/ckosloski/NfPcH/19041/ perhaps)
- [ ] Get the pictures displaying - in a carousel (like https://www.w3schools.com/bootstrap/bootstrap_carousel.asp).  The pictures will be in the room_attachments database in the room document.

BNSN-W002 in the prd database has both linked images and attachments

In couch, to get the attachment you can use the url like https://couchdb-prd.avs.byu.edu/room_attachments/BNSN-W002/bnsn-w012-1.jpg

- [ ] Add two buttons under the pictures - Upload Picture and Take Picture (maybe just a camera icon on that)  <input type="file" accept="image/*" capture="camera"> works I think to have your phone just take a picture

- [ ] Change the device squares on the bottom to be a table with the following columns:
Icon, Name, DisplayName, Attributes, Address, IP Address, [unnamed column]

Address = show what's in the DB
IP address = resolve the ip address

For Pis, if we could have a link to the dmm dashboard and a link to the control ui in the last column, that'd be great

- [ ] Make the builder tab actually work and save everything in the ui-config and the devices table as needed
- [ ] show badges on the devices with no ports set up (that have ports in their device type)
- [ ] move the list of devices to the bottom and the menu more static-service-now-like on the right (as we talked about john)

- [ ] Routing tab - change the backend so that you can pass it the list of devices and ports and have it return the picture rather than just get it from the database (so we can have a live picture)
- [ ] Routing tab - make it so you can double click on a device and see the device popup-

**Comment by mandersonpjm** [comment]
This task will be tabled until we can get SMEE in a more stable state.
