### ISSUE TITLE
Add alerts to blueberry and cherry UIs

### ISSUE THREAD

**Issue by thailandmatt** [byuoitav/team#996]
Whenever a user tries to initiate an action and it fails, show a popup with the message specified in the roadmap document

**Comment by jpw547** [comment]
I have added alerts to both UIs and have their messages coming from the database so they are configurable. I also moved my code into a different branch so that these pop-ups do not get deployed at the end of the sprint. 
**Next:** modify the request functions in the UIs so that the technical error information can be shown on the message.

**Comment by jpw547** [comment]
Did that part too.
